### ISSUE TITLE
What is the license?

### ISSUE THREAD

**Issue by hishamhm** [matiasvlevi/lu5#2]
The project looks really cool! What is the license of the sources?

I looked in the usual places (`README` file, `LICENSE` or `COPYING` files in the repo root, top comment in `src/main.c`) but couldn't find any info. It doesn't seem to be in the GitHub project metadata either. If there is no licensing information, could you please add it? Thank you!

(As an example, LuaRocks has licensing info in the README, the `COPYING` file, and the GitHub sidebar: https://github.com/luarocks/luarocks/ )

**Comment by matiasvlevi** [comment]
Totally forgot about the license, let's make it MIT
