### ISSUE TITLE
Reload Sketch

### ISSUE THREAD

**Issue by Tamnac** [matiasvlevi/lu5#3]
Having some button or keyboard shortcut within the sketch to reload it would help speed up iteration times a bunch, compared to killing and restarting it from the terminal.

**Comment by matiasvlevi** [comment]
You can now reload a sketch with `CTRL` + `R` as of commit 1262aa2

This is going to be included in the v0.1.6 release. 
In the mean time you can build from source and you should be able to restart your sketches!

**Comment by matiasvlevi** [comment]
closing
